name: Generate and deploy website

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'liberica'
          cache: maven
      - name: Build
        run: mvn -B clean install -DskipTests --file pom.xml
      - name: Site with Maven
        run: mvn -B -P site site:site --file pom.xml
      - name: Staging
        run: mvn -B site:stage --file pom.xml
      - name: Deduplicate
        run: mvn -P site web-resource-deduplicator:deduplicate
      - name: Publish
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./target/staging/"
          server-dir: "./web-resource-deduplicator-maven-plugin/"
